//------------------------------------------------------------------------------
// <auto-generated>
// Resources.g.cs
// Do not edit directly. This file has been auto-generated from .resx resources.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace Resources {

    /// <summary>Strings1 resources class</summary>
    [ScriptResources]
    [GeneratedCodeAttribute("ResXCodeBuilder", "1.0.0.0")]
    internal static class Strings1 {

        /// <summary>This is a string</summary>
        public static readonly string String1 = null;

        public static readonly string String2 = null;

        public static readonly string String3 = null;
    }
}
