//------------------------------------------------------------------------------
// <auto-generated>
// Resources.g.cs
// Do not edit directly. This file has been auto-generated from .resx resources.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace Resources {

    /// <summary>Strings2 resources class</summary>
    [ScriptResources]
    [GeneratedCodeAttribute("ResXCodeBuilder", "1.0.0.0")]
    public static class Strings2 {

        public static readonly string String1 = null;

        public static readonly string String2 = null;
    }
}
